spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/?currentSchema=acollyte
    username: acollyte
    password: femema
    driverClassName: org.postgresql.Driver
